"""Node 1: `intake` (graph-design.md, state-schema.md §3 "Initial values").

Writes the open `cases` row immediately, before any interrupt node exists in the graph, so
a resume never re-runs it (case-persistence.md §3 "Idempotency"). `ticket_id`/`thread_id`
are generated by `service.new_ticket()` before the graph is invoked, not here
(case-persistence.md §6) — `intake` only mirrors `config.thread_id` into state, per
state-schema.md §2.1.
"""

from __future__ import annotations

from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnableConfig

from autosupport.graph.state import AgentState
from autosupport.store import cases as cases_repo
from autosupport.store import db as store_db


def intake(state: AgentState, config: RunnableConfig) -> dict:
    ticket = state["ticket"]
    thread_id = config["configurable"]["thread_id"]
    conn = store_db.connect()
    try:
        cases_repo.insert_open(conn, state["ticket_id"], state["customer_id"], thread_id, ticket)
    finally:
        conn.close()

    return {
        "thread_id": thread_id,
        "status": "open",
        "messages": [HumanMessage(content=f"{ticket.subject}\n\n{ticket.body}")],
        "retrieval_round": 0,
        "clarification_count": 0,
        "verify_attempts": 0,
        "revision_count": 0,
        "tool_calls_this_round": 0,
        "user_acceptance": None,
    }
